### ISSUE TITLE
Allow require to resolve modules similar to nodejs

### ISSUE THREAD

**Issue by brentonhouse** [mobilehero/adamantium#3]
> As a developer,
> I want require to be able to find modules in the same way as nodejs
> So that I can install packages such as bluebird, lodash, or custom libraries from NPM in my application.

Unless I am missing something here, at compile time, you know all the libraries that could possibly be referenced. For all static includes, i.e. require("lodash") or require("../mylib"), you could easily map and change the requires to the correct path before packaging the app.
Dynamic requires, i.e. require(myvar + "mylib") would require a bit more effort such as creating a function that could lookup the desired library at runtime and use that with the relative folder to find it in a list of libraries in the app (assuming the list was generated at compile time.)
You could also look in the package.json files at compile time to see if there is a main referenced. Support for index.js could also be added at compile time.
I've tried a few of the methods such as [ti-commonjs](https://github.com/tonylukasavage/ti-commonjs) which look for things at runtime, but the performance hit from those was far too great.

Here is the nodejs load order that we need to support:  (from [https://nodejs.org/api/modules.html#modules_all_together](https://nodejs.org/api/modules.html#modules_all_together))

``` js
require(X) from module at path Y
1. If X is a core module,
   a. return the core module
   b. STOP
2. If X begins with './' or '/' or '../'
   a. LOAD_AS_FILE(Y + X)
   b. LOAD_AS_DIRECTORY(Y + X)
3. LOAD_NODE_MODULES(X, dirname(Y))
4. THROW "not found"

LOAD_AS_FILE(X)
1. If X is a file, load X as JavaScript text.  STOP
2. If X.js is a file, load X.js as JavaScript text.  STOP
3. If X.json is a file, parse X.json to a JavaScript Object.  STOP
4. If X.node is a file, load X.node as binary addon.  STOP

LOAD_AS_DIRECTORY(X)
1. If X/package.json is a file,
   a. Parse X/package.json, and look for "main" field.
   b. let M = X + (json main field)
   c. LOAD_AS_FILE(M)
2. If X/index.js is a file, load X/index.js as JavaScript text.  STOP
3. If X/index.json is a file, parse X/index.json to a JavaScript object. STOP
4. If X/index.node is a file, load X/index.node as binary addon.  STOP

LOAD_NODE_MODULES(X, START)
1. let DIRS=NODE_MODULES_PATHS(START)
2. for each DIR in DIRS:
   a. LOAD_AS_FILE(DIR/X)
   b. LOAD_AS_DIRECTORY(DIR/X)

NODE_MODULES_PATHS(START)
1. let PARTS = path split(START)
2. let I = count of PARTS - 1
3. let DIRS = []
4. while I >= 0,
   a. if PARTS[I] = "node_modules" CONTINUE
   c. DIR = path join(PARTS[0 .. I] + "node_modules")
   b. DIRS = DIRS + DIR
   c. let I = I - 1
5. return DIRS
```

Associated JIRA Ticket(s): 

https://jira.appcelerator.org/browse/TIMOB-20472
https://jira.appcelerator.org/browse/TIMOB-16078
https://jira.appcelerator.org/browse/TIMOB-19392

**Comment by FokkeZB** [comment]
Also see:
- https://jira.appcelerator.org/browse/TIMOB-16078
- https://github.com/tonylukasavage/ti-commonjs

**Comment by brentonhouse** [comment]
Thanks @FokkeZB!  [ti-commonjs](https://github.com/tonylukasavage/ti-commonjs) is what I actually started with a couple years ago but as soon as I started using it with Android, all the file reads slowed the app way down.  I saw your JIRA ticket sometime around then as well and thought it might be in the product soon.  I am sure my implementation of this will be somewhat "hacky" seeing as I am doing it in Alloy and not in Titanium but maybe it can be a stepping stone to something better.   I know you have a ton of good ideas floating around in your head so feel free to comment on anything you see that could potentially be done better!

**Comment by FokkeZB** [comment]
I think there's a two different things to this:
- With Alloy we there's things we can resolve from NPM modules during the **transpile** step, like widgets ([PR](https://github.com/appcelerator/alloy/pull/755) and maybe themes relatively simple.
- At **runtime**, since Titanium require is not NodeJS compatible, any CommonJS module requiring in other modules via relative paths or expecting it to resolve `node_modules` will fail. Apart from making Titanium require NodeJS compatible ([TIMOB-16078](https://jira.appcelerator.org/browse/TIMOB-16078)) we could also make [Titaniumifer](https://github.com/smclab/titaniumifier) part of the Alloy compile or even Titanium build process to read in a {{package.json}} and for everything used at run-time (flagged, detected or otherwise) run Titaniumifier to make it Titanium compatible before dumping it into `Resources`.

**Comment by brentonhouse** [comment]
Feature available for testing in the beta branch of Adamantium now.  

https://github.com/mobilehero/adamantium/blob/next/1.7.35/adamantium/features/support-for-nodejs-style-require.md
